let num1 = 10;
let num2 = 8;


//addition(+) 
console.log(`${num1} + ${num2} = ${num1 + num2} `);

//substration(-)
console.log(`${num1} - ${num2} = ${num1 - num2} `);

//multiplication(*)
console.log(`${num1} * ${num2} = ${num1 * num2} `);

//division
console.log(`${num1} / ${num2} = ${num1 / num2} `);

//modulus(%)
console.log(`${num1} % ${num2} = ${num1 % num2} `);

//exponetiation(**)
console.log(`${num1} ** ${num2} = ${num1 ** num2} `);

